baseurl = "https://legionviking.se/"
title = "Legion Viking"
theme = "legv"
languageCode = "sv"
enableRobotsTXT = true
diary = "Dagbok"
paginate = 20

[menu]
  [[menu.header]]
    name = "dokument"
    weight = 3
    url = "/docs"
  [[menu.header]]
    name = "dagbok"
    weight = 2
    url = "/diary"
  [[menu.header]]
    name = "moddlistor"
    weight = 1
    url = "/mods"

[params]
  Name = "Legion Viking"
  HeaderUsername = "legionär"
  HeaderHostname = "legionviking"
  About = "Ännu en arma community från Sverige."
  ProfilePicture = "/logo.png"
